name: navigation
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
    sdk: ^3.10.1
    flutter: ">=1.17.0"

resolution: workspace
dependencies:
    flutter:
        sdk: flutter
    auto_route: ^11.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0
    auto_route_generator: ^10.4.0
    build_runner: ^2.10.4

flutter:
