name: music_player_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.10.1

workspace:
    - core
    - core_ui
    - data
    - domain
    - navigation
    - features/player
    - features/main
    - features/home
    - features/search
    - features/user_collection
    - features/auth

dependencies:
    flutter:
        sdk: flutter
    core:
        path: ./core
    data: 
        path: ./data
    navigation:
        path: ./navigation

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0
    melos: ^7.3.0
melos:
    useRootAsPackage: true
    scripts:
        generate:
            steps:
                - melos exec -c 1 --scope="navigation" -- dart run build_runner build
                - melos exec -c 1 --scope="core" -- dart run slang
flutter:
    uses-material-design: true
    assets:
      - assets/song.mp3