name: music_player_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.10.1

workspace:
    - core
    - core_ui
    - data
    - domain
    - navigation
    - features/player
    - features/main
    - features/home
    - features/search
    - features/user_collection
    - features/auth

dependencies:
    flutter:
        sdk: flutter
    core:
        path: ./core
    core_ui:
        path: ./core_ui
    data: 
        path: ./data
    domain:
        path: ./domain
    navigation:
        path: ./navigation

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0
    melos: ^7.3.0
melos:
    ide:
      intellij:
        enabled: false
    useRootAsPackage: true
    scripts:
      generate_core:
        run: melos exec --scope="core" -- dart run slang

      generate_data:
        run: melos exec --scope="data" -- dart run build_runner build   

      generate_main:
        run: melos exec --scope="main" -- dart run build_runner build

      generate_home:
        run: melos exec --scope="home" -- dart run build_runner build

      generate_player:
        run: melos exec --scope="player" -- dart run build_runner build

      generate_search:
        run: melos exec --scope="search" -- dart run build_runner build

      generate_user_collection:
        run: melos exec --scope="user_collection" -- dart run build_runner build

      generate_auth:
        run: melos exec --scope="auth" -- dart run build_runner build

      generate_all:
        steps:
          - melos run generate_core
          - melos run generate_data
          - melos run generate_main
          - melos run generate_home
          - melos run generate_player
          - melos run generate_search
          - melos run generate_user_collection
          - melos run generate_auth
flutter:
    uses-material-design: true
    assets:
      - api_keys_dev.env
      - assets/song.mp3
      - assets/song_cover.jpg
      - assets/artist_cover.png