name: core
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
homepage:

environment:
    sdk: ^3.10.1
    flutter: ">=1.17.0"
resolution: workspace

dependencies:
    flutter:
        sdk: flutter
    slang: ^4.11.0
    slang_flutter: ^4.11.0
    flutter_bloc: ^9.1.1
    flutter_localizations:
        sdk: flutter
    get_it: ^9.1.1
    freezed_annotation: ^3.1.0
    flutter_dotenv: ^6.0.0

    domain:
        path: ./../domain


dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0

flutter:
