name: domain
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
    sdk: ^3.10.1

resolution: workspace

dependencies:
    path: ^1.9.0
    equatable: ^2.0.7

    core:
      path: ./../core

dev_dependencies:
    lints: ^6.0.0
    test: ^1.25.6
