name: domain
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
    sdk: ^3.10.1

resolution: workspace

dependencies:
    path: ^1.9.0
    just_audio: ^0.10.5
    just_audio_background: ^0.0.1-beta.17

    core:
      path: ./../core

dev_dependencies:
    lints: ^6.0.0
    test: ^1.25.6
