name: main
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
homepage:

environment:
    sdk: ^3.10.1
    flutter: ">=1.17.0"

dependencies:
    flutter:
        sdk: flutter

    domain:
        path: ./../../domain
    core:
        path: ./../../core
    core_ui:
        path: ./../../core_ui
    navigation:
        path: ./../../navigation
    player:
        path: ./../player

resolution: workspace

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0
    auto_route_generator: ^10.4.0
flutter:
