name: player
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
homepage:

environment:
    sdk: ^3.10.1
    flutter: ">=1.17.0"

resolution: workspace

dependencies:
    flutter:
        sdk: flutter
    just_audio: ^0.10.5
    navigation:
        path: ./../../navigation

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0
    auto_route_generator: ^10.4.0

flutter:
