name: auth
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  core:
      path: ./../../core
  core_ui:
      path: ./../../core_ui
  domain:
      path: ./../../domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  auto_route_generator: ^10.4.0
  freezed: ^3.2.3


flutter:
